# Generated by Django 4.0.2 on 2022-02-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_box_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='source',
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='no instructions'),
        ),
        migrations.DeleteModel(
            name='Instruction',
        ),
    ]
